name: manuel_route_builder
description: A Flutter package for creating manual routes on Google Maps with circle or free-draw area selection and nearest neighbor routing.
version: 1.0.3
homepage: https://github.com/BurakAkten/manuel_route_builder.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.16.0
  maps_toolkit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

